import React, { useState, useCallback, useMemo } from 'react';
import { Lightbulb, Zap, Clock, Code, CheckCircle, Loader2, Sparkles, Download, X } from 'lucide-react';

interface ProjectProposal {
  title: string;
  overview: string;
  techStack: string[];
  features: string[];
  timeline: string;
  approach: string;
  estimatedCost: string;
}

// System prompt moved outside component to avoid recreation on each render
const SYSTEM_PROMPT = `You are a project proposal assistant for Imran Khan, a Front-End Engineer specializing in React, Vue, TypeScript, StencilJS, and Python.

When given a project idea, create a detailed technical proposal in JSON format with:
- title: A catchy project name
- overview: 2-3 sentences explaining what the project does
- techStack: Array of 4-6 technologies Imran would use (focus on React, Vue, TypeScript, StencilJS, Python, and modern tools)
- features: Array of 5-7 key features the project would include
- timeline: Estimated timeline (e.g., "4-6 weeks")
- approach: 2-3 sentences describing Imran's development approach
- estimatedCost: A range like "$5,000 - $8,000" or "Contact for quote"

Make it professional, specific, and tailored to Imran's tech stack. Be realistic about complexity and timelines.

IMPORTANT: Respond ONLY with valid JSON. No markdown, no backticks, no preamble. Just the JSON object.`;

// Example ideas moved outside component (constant data)
const EXAMPLE_IDEAS = [
  "A real-time collaboration tool for remote teams",
  "An AI-powered content management system",
  "A mobile-first booking platform for restaurants",
  "A cryptocurrency portfolio tracker with alerts"
] as const;

const ProjectProposalGenerator: React.FC = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [projectIdea, setProjectIdea] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [proposal, setProposal] = useState<ProjectProposal | null>(null);
  const [error, setError] = useState<string | null>(null);

  // Memoized check for valid input
  const canGenerate = useMemo(() => projectIdea.trim().length > 10, [projectIdea]);

  // useCallback prevents function recreation on each render
  const generateProposal = useCallback(async () => {
    if (!canGenerate) return;

    setIsGenerating(true);
    setError(null);

    try {
      const response = await fetch('https://api.anthropic.com/v1/messages', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          model: 'claude-sonnet-4-20250514',
          max_tokens: 2000,
          system: SYSTEM_PROMPT,
          messages: [{
            role: 'user',
            content: `Create a detailed project proposal for this idea: "${projectIdea}"`
          }]
        })
      });

      if (!response.ok) {
        throw new Error(`API error: ${response.status}`);
      }

      const data = await response.json();

      if (!data.content?.[0]?.text) {
        throw new Error('Invalid response format');
      }

      // Clean and parse response
      const text = data.content[0].text.replace(/```json|```/g, '').trim();
      const proposalData: ProjectProposal = JSON.parse(text);

      // Validate proposal has required fields
      if (!proposalData.title || !proposalData.techStack) {
        throw new Error('Invalid proposal data');
      }

      setProposal(proposalData);
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Failed to generate proposal';
      setError(message);
      console.error('Proposal generation error:', err);
    } finally {
      setIsGenerating(false);
    }
  }, [projectIdea, canGenerate]);

  const downloadProposal = useCallback(() => {
    if (!proposal) return;

    const content = `PROJECT PROPOSAL
Generated by Imran Khan's Portfolio Assistant

${proposal.title}
${'='.repeat(proposal.title.length)}

OVERVIEW
${proposal.overview}

TECH STACK
${proposal.techStack.map(tech => `• ${tech}`).join('\n')}

KEY FEATURES
${proposal.features.map((feature, idx) => `${idx + 1}. ${feature}`).join('\n')}

TIMELINE
${proposal.timeline}

APPROACH
${proposal.approach}

ESTIMATED INVESTMENT
${proposal.estimatedCost}

---
Ready to discuss this project? Contact Imran Khan at softwarerebel.com`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `proposal-${proposal.title.toLowerCase().replace(/\s+/g, '-')}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  }, [proposal]);

  const handleReset = useCallback(() => {
    setProjectIdea('');
    setProposal(null);
    setError(null);
  }, []);

  const handleClose = useCallback(() => {
    setIsOpen(false);
    // Reset after animation completes
    setTimeout(() => {
      setProjectIdea('');
      setProposal(null);
      setError(null);
    }, 300);
  }, []);

  // Floating button (closed state)
  if (!isOpen) {
    return (
      <div className="fixed top-24 right-6 z-40">
        <button
          onClick={() => setIsOpen(true)}
          className="relative bg-primary hover:bg-primary-glow text-primary-foreground rounded-full p-3 shadow-lg transition-all hover:scale-110 flex items-center gap-2 group overflow-hidden border border-primary/20"
          style={{
            boxShadow: '0 0 20px hsl(var(--primary) / 0.3)',
            transition: 'var(--transition-smooth)'
          }}
          aria-label="Open project proposal generator"
          title="Generate Project Proposal"
        >
          <div className="absolute inset-0 bg-primary-glow opacity-0 group-hover:opacity-20 blur-2xl transition-opacity" />
          <Lightbulb size={20} className="relative z-10" />
          <span className="relative z-10 font-medium text-sm hidden lg:inline">Project Ideas</span>
        </button>
      </div>
    );
  }

  // Modal (open state)
  return (
    <div className="fixed inset-0 bg-background/90 backdrop-blur-md z-50 flex items-center justify-center p-4">
      <div
        className="bg-card border border-border rounded-xl w-full max-w-4xl max-h-[90vh] flex flex-col shadow-2xl"
        style={{ boxShadow: '0 0 40px hsl(var(--primary) / 0.2)' }}
      >
        {/* Header */}
        <div
          className="bg-gradient-to-r from-primary via-primary-glow to-primary text-primary-foreground p-6 rounded-t-xl flex justify-between items-center relative overflow-hidden"
          style={{ boxShadow: '0 0 30px hsl(var(--primary) / 0.4)' }}
        >
          <div className="absolute inset-0 bg-primary-glow opacity-10 blur-3xl" />
          <div className="relative z-10">
            <h2 className="text-2xl font-bold font-inter flex items-center gap-3">
              <Lightbulb size={28} />
              Project Proposal Generator
            </h2>
            <p className="text-sm opacity-90 mt-1 font-mono">
              Describe your idea, get a detailed technical proposal
            </p>
          </div>
          <button
            onClick={handleClose}
            className="relative z-10 hover:bg-primary-foreground/10 p-2 rounded-lg transition-all"
            aria-label="Close generator"
          >
            <X size={24} />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6">
          {!proposal ? (
            <div className="space-y-6">
              {/* Input Section */}
              <div className="bg-background/50 backdrop-blur-sm border border-border rounded-lg p-6">
                <label className="block text-sm font-semibold text-foreground mb-3 font-inter">
                  What do you want to build?
                </label>
                <textarea
                  value={projectIdea}
                  onChange={(e) => setProjectIdea(e.target.value)}
                  placeholder="Example: I need a dashboard for my e-commerce business that shows real-time sales, inventory levels, and customer analytics. It should work on mobile and desktop."
                  className="w-full bg-background border border-input rounded-lg px-4 py-3 text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring font-inter text-sm min-h-[150px] resize-y"
                  disabled={isGenerating}
                />
                <p className="text-xs text-muted-foreground mt-2 font-mono">
                  Be specific. Minimum 10 characters required.
                </p>
              </div>

              {/* Error Display */}
              {error && (
                <div className="bg-destructive/10 border border-destructive/30 rounded-lg p-4 text-destructive text-sm">
                  {error}
                </div>
              )}

              {/* Generate Button */}
              <button
                onClick={generateProposal}
                disabled={!canGenerate || isGenerating}
                className="w-full bg-primary hover:bg-primary-glow disabled:bg-muted disabled:cursor-not-allowed text-primary-foreground py-4 rounded-lg transition-all flex items-center justify-center gap-3 font-semibold text-lg group relative overflow-hidden"
                style={{
                  boxShadow: '0 0 20px hsl(var(--primary) / 0.3)',
                  transition: 'var(--transition-smooth)'
                }}
              >
                <div className="absolute inset-0 bg-primary-glow opacity-0 group-hover:opacity-20 blur-2xl transition-opacity" />
                {isGenerating ? (
                  <>
                    <Loader2 size={24} className="animate-spin relative z-10" />
                    <span className="relative z-10">Generating Proposal...</span>
                  </>
                ) : (
                  <>
                    <Sparkles size={24} className="relative z-10" />
                    <span className="relative z-10">Generate Project Proposal</span>
                  </>
                )}
              </button>

              {/* Examples */}
              <div className="bg-background/30 backdrop-blur-sm border border-border/50 rounded-lg p-4">
                <h3 className="text-sm font-semibold text-muted-foreground mb-3 font-inter">
                  Example Ideas:
                </h3>
                <div className="space-y-2">
                  {EXAMPLE_IDEAS.map((example) => (
                    <button
                      key={example}
                      onClick={() => setProjectIdea(example)}
                      disabled={isGenerating}
                      className="w-full text-left text-sm text-foreground hover:text-primary hover:bg-primary/5 px-3 py-2 rounded transition-all border border-transparent hover:border-primary/30 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                      {example}
                    </button>
                  ))}
                </div>
              </div>
            </div>
          ) : (
            <ProposalDisplay
              proposal={proposal}
              onDownload={downloadProposal}
              onReset={handleReset}
            />
          )}
        </div>
      </div>
    </div>
  );
};

// Extracted proposal display component for better organization
const ProposalDisplay: React.FC<{
  proposal: ProjectProposal;
  onDownload: () => void;
  onReset: () => void;
}> = ({ proposal, onDownload, onReset }) => (
  <div className="space-y-6 fade-in-up">
    {/* Title */}
    <div className="text-center">
      <h3 className="text-3xl font-bold text-gradient mb-2">{proposal.title}</h3>
      <p className="text-muted-foreground font-mono text-sm">Custom proposal generated for you</p>
    </div>

    {/* Overview */}
    <Section icon={Sparkles} title="Project Overview">
      <p className="text-foreground leading-relaxed">{proposal.overview}</p>
    </Section>

    {/* Tech Stack */}
    <Section icon={Code} title="Recommended Tech Stack">
      <div className="flex flex-wrap gap-2">
        {proposal.techStack.map((tech) => (
          <span
            key={tech}
            className="bg-primary/10 border border-primary/30 text-primary px-3 py-1 rounded-full text-sm font-medium font-mono"
          >
            {tech}
          </span>
        ))}
      </div>
    </Section>

    {/* Features */}
    <Section icon={CheckCircle} title="Key Features">
      <div className="space-y-2">
        {proposal.features.map((feature, idx) => (
          <div key={idx} className="flex items-start gap-3">
            <div className="w-6 h-6 rounded-full bg-primary/20 flex items-center justify-center flex-shrink-0 mt-0.5">
              <span className="text-primary text-xs font-bold">{idx + 1}</span>
            </div>
            <p className="text-foreground text-sm leading-relaxed">{feature}</p>
          </div>
        ))}
      </div>
    </Section>

    {/* Timeline & Cost */}
    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
      <InfoCard icon={Clock} title="Timeline" value={proposal.timeline} />
      <InfoCard icon={Zap} title="Investment" value={proposal.estimatedCost} />
    </div>

    {/* Approach */}
    <Section title="Development Approach">
      <p className="text-foreground leading-relaxed">{proposal.approach}</p>
    </Section>

    {/* CTA */}
    <div className="bg-gradient-to-r from-primary/10 to-primary-glow/10 border border-primary/30 rounded-lg p-6 text-center">
      <p className="text-foreground mb-4 font-inter">
        Ready to bring this project to life? Let's discuss the details.
      </p>
      <div className="flex flex-col sm:flex-row gap-3 justify-center">
        <button
          onClick={onDownload}
          className="bg-primary hover:bg-primary-glow text-primary-foreground px-6 py-3 rounded-lg transition-all flex items-center justify-center gap-2 font-semibold"
          style={{ boxShadow: '0 0 15px hsl(var(--primary) / 0.3)' }}
        >
          <Download size={18} />
          Download Proposal
        </button>
        <button
          onClick={onReset}
          className="bg-secondary hover:bg-secondary/80 text-secondary-foreground px-6 py-3 rounded-lg transition-all font-semibold"
        >
          Generate Another
        </button>
      </div>
    </div>
  </div>
);

// Reusable Section component
const Section: React.FC<{
  icon?: React.ComponentType<any>;
  title: string;
  children: React.ReactNode;
}> = ({ icon: Icon, title, children }) => (
  <div className="bg-background/50 backdrop-blur-sm border border-border rounded-lg p-6">
    <h4 className="text-lg font-bold text-foreground mb-3 font-inter flex items-center gap-2">
      {Icon && <Icon size={20} className="text-primary" />}
      {title}
    </h4>
    {children}
  </div>
);

// Reusable InfoCard component
const InfoCard: React.FC<{
  icon: React.ComponentType<any>;
  title: string;
  value: string;
}> = ({ icon: Icon, title, value }) => (
  <div className="bg-background/50 backdrop-blur-sm border border-border rounded-lg p-6">
    <h4 className="text-lg font-bold text-foreground mb-3 font-inter flex items-center gap-2">
      <Icon size={20} className="text-primary" />
      {title}
    </h4>
    <p className="text-2xl font-bold text-primary">{value}</p>
  </div>
);

export default ProjectProposalGenerator;
